server:
  port : 8080

security:
  jwt:
    enabled: true
    secret: abcbank
  user-otp:
    code: 123456

spring:
  main:
    allow-circular-references: true
  datasource:
    url: jdbc:mysql://localhost:3306/abcbankdb
    username: root
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true